// <auto-generated />
using System;
using Messenger.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Messenger.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240610175829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationType")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PrivateConversationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.HasIndex("PrivateConversationId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.ParticipentInGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("ParticipentsInGroups");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.PrivateConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Member1Id")
                        .HasColumnType("int");

                    b.Property<int>("Member2Id")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantsInPrivateConversationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Member1Id");

                    b.HasIndex("Member2Id");

                    b.ToTable("PrivateConversations");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.UserContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("UserContactId")
                        .HasColumnType("int");

                    b.Property<int?>("UserContactOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserContactId");

                    b.HasIndex("UserContactOwnerId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Conversation", b =>
                {
                    b.HasOne("Messenger.Infrastructure.Entities.Group", "Group")
                        .WithOne("Conversation")
                        .HasForeignKey("Messenger.Infrastructure.Entities.Conversation", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messenger.Infrastructure.Entities.PrivateConversation", "PrivateConversation")
                        .WithOne("Conversation")
                        .HasForeignKey("Messenger.Infrastructure.Entities.Conversation", "PrivateConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("PrivateConversation");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Message", b =>
                {
                    b.HasOne("Messenger.Infrastructure.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messenger.Infrastructure.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.ParticipentInGroup", b =>
                {
                    b.HasOne("Messenger.Infrastructure.Entities.Group", "Group")
                        .WithMany("ParticipantsInGroup")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Messenger.Infrastructure.Entities.User", "User")
                        .WithMany("ParticipantsInGroup")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.PrivateConversation", b =>
                {
                    b.HasOne("Messenger.Infrastructure.Entities.User", "Member1")
                        .WithMany()
                        .HasForeignKey("Member1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Messenger.Infrastructure.Entities.User", "Member2")
                        .WithMany()
                        .HasForeignKey("Member2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Member1");

                    b.Navigation("Member2");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.UserContact", b =>
                {
                    b.HasOne("Messenger.Infrastructure.Entities.User", "Contact")
                        .WithMany("Contacts")
                        .HasForeignKey("UserContactId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Messenger.Infrastructure.Entities.User", "ContactOwner")
                        .WithMany()
                        .HasForeignKey("UserContactOwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Contact");

                    b.Navigation("ContactOwner");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.Group", b =>
                {
                    b.Navigation("Conversation");

                    b.Navigation("ParticipantsInGroup");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.PrivateConversation", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Messenger.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Messages");

                    b.Navigation("ParticipantsInGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
